site_name: 风雨阁Storm Pavilion | 文档
theme:
  language: zh
  name: material
  highlightjs: true
  palette:
    primary: green
    accent: deep purple
  favicon: https://spcraft.ml/favicon.ico
  logo: https://spcraft.ml/favicon.ico
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.share
    - search.suggest
repo_url: https://github.com/SPCraftMC/Docs
edit_uri: 'tree/main/docs/'
repo_name: GitHub
plugins:
  - tags
  - search