site_name: 风雨阁Storm Pavilion 2 | 文档
theme:
  language: zh
  name: material
  highlightjs: true
  palette:
    - media: "(prefers-color-scheme)"
      primary: green
      accent: light green
      toggle:
        icon: material/brightness-auto
        name: 跟随系统
    - media: "(prefers-color-scheme: light)"
      primary: green
      accent: light green
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: 暗色模式
    - media: "(prefers-color-scheme: dark)"
      primary: green
      accent: light green
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: 暗色模式
  favicon: https://spcraft.1l1.icu/favicon.ico
  logo: https://spcraft.1l1.icu/favicon.ico
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.share
    - search.suggest
repo_url: https://github.com/SPCraftMC/Docs
edit_uri: 'tree/main/docs/'
repo_name: GitHub
plugins:
  - tags
  - search
markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.superfences