site_name: 风雨阁Storm Pavilion 2 | 文档
theme:
  language: zh
  name: material
  highlightjs: true
  palette:
    primary: green
    accent: deep purple
  favicon: https://spcraft.1l1.icu/favicon.ico
  logo: https://spcraft.1l1.icu/favicon.ico
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.share
    - search.suggest
repo_url: https://github.com/SPCraftMC/Docs
edit_uri: 'tree/main/docs/'
repo_name: GitHub
plugins:
  - tags
  - search
markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.superfences